package com.cloudE.mapper;

import com.cloudE.entity.Memberfides;
import com.cloudE.entity.MemberfidesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MemberfidesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    long countByExample(MemberfidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    int deleteByExample(MemberfidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    int insert(Memberfides record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    int insertSelective(Memberfides record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    List<Memberfides> selectByExample(MemberfidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    Memberfides selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") Memberfides record, @Param("example") MemberfidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    int updateByExample(@Param("record") Memberfides record, @Param("example") MemberfidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    int updateByPrimaryKeySelective(Memberfides record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    int updateByPrimaryKey(Memberfides record);
}