server:
  port: 8888

spring:
  profiles:
    active: local
  application:
    name: cloudE-config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/zunzhuowei/cloudE.git
            searchPaths: cloudE-config-repo
            lable: master

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
