server:
  port: 8082

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.cloudE.mapper

eureka:
  instance:
    prefer-ip-address: true

#动态传入参数测试
ucTask:
  dynamicParameter: 1