package com.cloudE.entity;

import java.io.Serializable;

public class Memberfides implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.mid
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.name
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.sex
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.btd
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String btd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.city
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.icon
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.invite
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Integer invite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.gp
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Byte gp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.sta
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Integer sta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.mtime
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Long mtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.email
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.bindtime
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Integer bindtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.tel
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.realname
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.identity
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.yellowvip
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Byte yellowvip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.isyearvip
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Byte isyearvip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.passwd
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.salt
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.lgtm
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Integer lgtm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.lxlg
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Integer lxlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.qq
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.address
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.regip
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Long regip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberfides0.active_assets
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private Byte activeAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.mid
     *
     * @return the value of memberfides0.mid
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.mid
     *
     * @param mid the value for memberfides0.mid
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.name
     *
     * @return the value of memberfides0.name
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.name
     *
     * @param name the value for memberfides0.name
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.sex
     *
     * @return the value of memberfides0.sex
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.sex
     *
     * @param sex the value for memberfides0.sex
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.btd
     *
     * @return the value of memberfides0.btd
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getBtd() {
        return btd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.btd
     *
     * @param btd the value for memberfides0.btd
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setBtd(String btd) {
        this.btd = btd == null ? null : btd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.city
     *
     * @return the value of memberfides0.city
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.city
     *
     * @param city the value for memberfides0.city
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.icon
     *
     * @return the value of memberfides0.icon
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.icon
     *
     * @param icon the value for memberfides0.icon
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.invite
     *
     * @return the value of memberfides0.invite
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Integer getInvite() {
        return invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.invite
     *
     * @param invite the value for memberfides0.invite
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setInvite(Integer invite) {
        this.invite = invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.gp
     *
     * @return the value of memberfides0.gp
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Byte getGp() {
        return gp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.gp
     *
     * @param gp the value for memberfides0.gp
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setGp(Byte gp) {
        this.gp = gp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.sta
     *
     * @return the value of memberfides0.sta
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Integer getSta() {
        return sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.sta
     *
     * @param sta the value for memberfides0.sta
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setSta(Integer sta) {
        this.sta = sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.mtime
     *
     * @return the value of memberfides0.mtime
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Long getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.mtime
     *
     * @param mtime the value for memberfides0.mtime
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setMtime(Long mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.email
     *
     * @return the value of memberfides0.email
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.email
     *
     * @param email the value for memberfides0.email
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.bindtime
     *
     * @return the value of memberfides0.bindtime
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Integer getBindtime() {
        return bindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.bindtime
     *
     * @param bindtime the value for memberfides0.bindtime
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setBindtime(Integer bindtime) {
        this.bindtime = bindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.tel
     *
     * @return the value of memberfides0.tel
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.tel
     *
     * @param tel the value for memberfides0.tel
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.realname
     *
     * @return the value of memberfides0.realname
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.realname
     *
     * @param realname the value for memberfides0.realname
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.identity
     *
     * @return the value of memberfides0.identity
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.identity
     *
     * @param identity the value for memberfides0.identity
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.yellowvip
     *
     * @return the value of memberfides0.yellowvip
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Byte getYellowvip() {
        return yellowvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.yellowvip
     *
     * @param yellowvip the value for memberfides0.yellowvip
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setYellowvip(Byte yellowvip) {
        this.yellowvip = yellowvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.isyearvip
     *
     * @return the value of memberfides0.isyearvip
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Byte getIsyearvip() {
        return isyearvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.isyearvip
     *
     * @param isyearvip the value for memberfides0.isyearvip
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setIsyearvip(Byte isyearvip) {
        this.isyearvip = isyearvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.passwd
     *
     * @return the value of memberfides0.passwd
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.passwd
     *
     * @param passwd the value for memberfides0.passwd
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.salt
     *
     * @return the value of memberfides0.salt
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.salt
     *
     * @param salt the value for memberfides0.salt
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.lgtm
     *
     * @return the value of memberfides0.lgtm
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Integer getLgtm() {
        return lgtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.lgtm
     *
     * @param lgtm the value for memberfides0.lgtm
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setLgtm(Integer lgtm) {
        this.lgtm = lgtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.lxlg
     *
     * @return the value of memberfides0.lxlg
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Integer getLxlg() {
        return lxlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.lxlg
     *
     * @param lxlg the value for memberfides0.lxlg
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setLxlg(Integer lxlg) {
        this.lxlg = lxlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.qq
     *
     * @return the value of memberfides0.qq
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.qq
     *
     * @param qq the value for memberfides0.qq
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.address
     *
     * @return the value of memberfides0.address
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.address
     *
     * @param address the value for memberfides0.address
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.regip
     *
     * @return the value of memberfides0.regip
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Long getRegip() {
        return regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.regip
     *
     * @param regip the value for memberfides0.regip
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setRegip(Long regip) {
        this.regip = regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberfides0.active_assets
     *
     * @return the value of memberfides0.active_assets
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Byte getActiveAssets() {
        return activeAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberfides0.active_assets
     *
     * @param activeAssets the value for memberfides0.active_assets
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setActiveAssets(Byte activeAssets) {
        this.activeAssets = activeAssets;
    }

    @Override
    public String toString() {
        return "Memberfides{" +
                "mid=" + mid +
                ", name='" + name + '\'' +
                ", sex=" + sex +
                ", btd='" + btd + '\'' +
                ", city='" + city + '\'' +
                ", icon='" + icon + '\'' +
                ", invite=" + invite +
                ", gp=" + gp +
                ", sta=" + sta +
                ", mtime=" + mtime +
                ", email='" + email + '\'' +
                ", bindtime=" + bindtime +
                ", tel='" + tel + '\'' +
                ", realname='" + realname + '\'' +
                ", identity='" + identity + '\'' +
                ", yellowvip=" + yellowvip +
                ", isyearvip=" + isyearvip +
                ", passwd='" + passwd + '\'' +
                ", salt='" + salt + '\'' +
                ", lgtm=" + lgtm +
                ", lxlg=" + lxlg +
                ", qq='" + qq + '\'' +
                ", address='" + address + '\'' +
                ", regip=" + regip +
                ", activeAssets=" + activeAssets +
                '}';
    }

}