package com.cloudE.entity;

import java.util.ArrayList;
import java.util.List;

public class MemberfidesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public MemberfidesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMidIsNull() {
            addCriterion("mid is null");
            return (Criteria) this;
        }

        public Criteria andMidIsNotNull() {
            addCriterion("mid is not null");
            return (Criteria) this;
        }

        public Criteria andMidEqualTo(Integer value) {
            addCriterion("mid =", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotEqualTo(Integer value) {
            addCriterion("mid <>", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThan(Integer value) {
            addCriterion("mid >", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mid >=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThan(Integer value) {
            addCriterion("mid <", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThanOrEqualTo(Integer value) {
            addCriterion("mid <=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidIn(List<Integer> values) {
            addCriterion("mid in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotIn(List<Integer> values) {
            addCriterion("mid not in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidBetween(Integer value1, Integer value2) {
            addCriterion("mid between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotBetween(Integer value1, Integer value2) {
            addCriterion("mid not between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Byte value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Byte value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Byte value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Byte value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Byte value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Byte value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Byte> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Byte> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Byte value1, Byte value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Byte value1, Byte value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBtdIsNull() {
            addCriterion("btd is null");
            return (Criteria) this;
        }

        public Criteria andBtdIsNotNull() {
            addCriterion("btd is not null");
            return (Criteria) this;
        }

        public Criteria andBtdEqualTo(String value) {
            addCriterion("btd =", value, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdNotEqualTo(String value) {
            addCriterion("btd <>", value, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdGreaterThan(String value) {
            addCriterion("btd >", value, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdGreaterThanOrEqualTo(String value) {
            addCriterion("btd >=", value, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdLessThan(String value) {
            addCriterion("btd <", value, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdLessThanOrEqualTo(String value) {
            addCriterion("btd <=", value, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdLike(String value) {
            addCriterion("btd like", value, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdNotLike(String value) {
            addCriterion("btd not like", value, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdIn(List<String> values) {
            addCriterion("btd in", values, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdNotIn(List<String> values) {
            addCriterion("btd not in", values, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdBetween(String value1, String value2) {
            addCriterion("btd between", value1, value2, "btd");
            return (Criteria) this;
        }

        public Criteria andBtdNotBetween(String value1, String value2) {
            addCriterion("btd not between", value1, value2, "btd");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andIconIsNull() {
            addCriterion("icon is null");
            return (Criteria) this;
        }

        public Criteria andIconIsNotNull() {
            addCriterion("icon is not null");
            return (Criteria) this;
        }

        public Criteria andIconEqualTo(String value) {
            addCriterion("icon =", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotEqualTo(String value) {
            addCriterion("icon <>", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThan(String value) {
            addCriterion("icon >", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThanOrEqualTo(String value) {
            addCriterion("icon >=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThan(String value) {
            addCriterion("icon <", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThanOrEqualTo(String value) {
            addCriterion("icon <=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLike(String value) {
            addCriterion("icon like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotLike(String value) {
            addCriterion("icon not like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconIn(List<String> values) {
            addCriterion("icon in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotIn(List<String> values) {
            addCriterion("icon not in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconBetween(String value1, String value2) {
            addCriterion("icon between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotBetween(String value1, String value2) {
            addCriterion("icon not between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andInviteIsNull() {
            addCriterion("invite is null");
            return (Criteria) this;
        }

        public Criteria andInviteIsNotNull() {
            addCriterion("invite is not null");
            return (Criteria) this;
        }

        public Criteria andInviteEqualTo(Integer value) {
            addCriterion("invite =", value, "invite");
            return (Criteria) this;
        }

        public Criteria andInviteNotEqualTo(Integer value) {
            addCriterion("invite <>", value, "invite");
            return (Criteria) this;
        }

        public Criteria andInviteGreaterThan(Integer value) {
            addCriterion("invite >", value, "invite");
            return (Criteria) this;
        }

        public Criteria andInviteGreaterThanOrEqualTo(Integer value) {
            addCriterion("invite >=", value, "invite");
            return (Criteria) this;
        }

        public Criteria andInviteLessThan(Integer value) {
            addCriterion("invite <", value, "invite");
            return (Criteria) this;
        }

        public Criteria andInviteLessThanOrEqualTo(Integer value) {
            addCriterion("invite <=", value, "invite");
            return (Criteria) this;
        }

        public Criteria andInviteIn(List<Integer> values) {
            addCriterion("invite in", values, "invite");
            return (Criteria) this;
        }

        public Criteria andInviteNotIn(List<Integer> values) {
            addCriterion("invite not in", values, "invite");
            return (Criteria) this;
        }

        public Criteria andInviteBetween(Integer value1, Integer value2) {
            addCriterion("invite between", value1, value2, "invite");
            return (Criteria) this;
        }

        public Criteria andInviteNotBetween(Integer value1, Integer value2) {
            addCriterion("invite not between", value1, value2, "invite");
            return (Criteria) this;
        }

        public Criteria andGpIsNull() {
            addCriterion("gp is null");
            return (Criteria) this;
        }

        public Criteria andGpIsNotNull() {
            addCriterion("gp is not null");
            return (Criteria) this;
        }

        public Criteria andGpEqualTo(Byte value) {
            addCriterion("gp =", value, "gp");
            return (Criteria) this;
        }

        public Criteria andGpNotEqualTo(Byte value) {
            addCriterion("gp <>", value, "gp");
            return (Criteria) this;
        }

        public Criteria andGpGreaterThan(Byte value) {
            addCriterion("gp >", value, "gp");
            return (Criteria) this;
        }

        public Criteria andGpGreaterThanOrEqualTo(Byte value) {
            addCriterion("gp >=", value, "gp");
            return (Criteria) this;
        }

        public Criteria andGpLessThan(Byte value) {
            addCriterion("gp <", value, "gp");
            return (Criteria) this;
        }

        public Criteria andGpLessThanOrEqualTo(Byte value) {
            addCriterion("gp <=", value, "gp");
            return (Criteria) this;
        }

        public Criteria andGpIn(List<Byte> values) {
            addCriterion("gp in", values, "gp");
            return (Criteria) this;
        }

        public Criteria andGpNotIn(List<Byte> values) {
            addCriterion("gp not in", values, "gp");
            return (Criteria) this;
        }

        public Criteria andGpBetween(Byte value1, Byte value2) {
            addCriterion("gp between", value1, value2, "gp");
            return (Criteria) this;
        }

        public Criteria andGpNotBetween(Byte value1, Byte value2) {
            addCriterion("gp not between", value1, value2, "gp");
            return (Criteria) this;
        }

        public Criteria andStaIsNull() {
            addCriterion("sta is null");
            return (Criteria) this;
        }

        public Criteria andStaIsNotNull() {
            addCriterion("sta is not null");
            return (Criteria) this;
        }

        public Criteria andStaEqualTo(Integer value) {
            addCriterion("sta =", value, "sta");
            return (Criteria) this;
        }

        public Criteria andStaNotEqualTo(Integer value) {
            addCriterion("sta <>", value, "sta");
            return (Criteria) this;
        }

        public Criteria andStaGreaterThan(Integer value) {
            addCriterion("sta >", value, "sta");
            return (Criteria) this;
        }

        public Criteria andStaGreaterThanOrEqualTo(Integer value) {
            addCriterion("sta >=", value, "sta");
            return (Criteria) this;
        }

        public Criteria andStaLessThan(Integer value) {
            addCriterion("sta <", value, "sta");
            return (Criteria) this;
        }

        public Criteria andStaLessThanOrEqualTo(Integer value) {
            addCriterion("sta <=", value, "sta");
            return (Criteria) this;
        }

        public Criteria andStaIn(List<Integer> values) {
            addCriterion("sta in", values, "sta");
            return (Criteria) this;
        }

        public Criteria andStaNotIn(List<Integer> values) {
            addCriterion("sta not in", values, "sta");
            return (Criteria) this;
        }

        public Criteria andStaBetween(Integer value1, Integer value2) {
            addCriterion("sta between", value1, value2, "sta");
            return (Criteria) this;
        }

        public Criteria andStaNotBetween(Integer value1, Integer value2) {
            addCriterion("sta not between", value1, value2, "sta");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Long value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Long value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Long value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Long value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Long value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Long value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Long> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Long> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Long value1, Long value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Long value1, Long value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andBindtimeIsNull() {
            addCriterion("bindtime is null");
            return (Criteria) this;
        }

        public Criteria andBindtimeIsNotNull() {
            addCriterion("bindtime is not null");
            return (Criteria) this;
        }

        public Criteria andBindtimeEqualTo(Integer value) {
            addCriterion("bindtime =", value, "bindtime");
            return (Criteria) this;
        }

        public Criteria andBindtimeNotEqualTo(Integer value) {
            addCriterion("bindtime <>", value, "bindtime");
            return (Criteria) this;
        }

        public Criteria andBindtimeGreaterThan(Integer value) {
            addCriterion("bindtime >", value, "bindtime");
            return (Criteria) this;
        }

        public Criteria andBindtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("bindtime >=", value, "bindtime");
            return (Criteria) this;
        }

        public Criteria andBindtimeLessThan(Integer value) {
            addCriterion("bindtime <", value, "bindtime");
            return (Criteria) this;
        }

        public Criteria andBindtimeLessThanOrEqualTo(Integer value) {
            addCriterion("bindtime <=", value, "bindtime");
            return (Criteria) this;
        }

        public Criteria andBindtimeIn(List<Integer> values) {
            addCriterion("bindtime in", values, "bindtime");
            return (Criteria) this;
        }

        public Criteria andBindtimeNotIn(List<Integer> values) {
            addCriterion("bindtime not in", values, "bindtime");
            return (Criteria) this;
        }

        public Criteria andBindtimeBetween(Integer value1, Integer value2) {
            addCriterion("bindtime between", value1, value2, "bindtime");
            return (Criteria) this;
        }

        public Criteria andBindtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("bindtime not between", value1, value2, "bindtime");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNull() {
            addCriterion("realname is null");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNotNull() {
            addCriterion("realname is not null");
            return (Criteria) this;
        }

        public Criteria andRealnameEqualTo(String value) {
            addCriterion("realname =", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotEqualTo(String value) {
            addCriterion("realname <>", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThan(String value) {
            addCriterion("realname >", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("realname >=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThan(String value) {
            addCriterion("realname <", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThanOrEqualTo(String value) {
            addCriterion("realname <=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLike(String value) {
            addCriterion("realname like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotLike(String value) {
            addCriterion("realname not like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameIn(List<String> values) {
            addCriterion("realname in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotIn(List<String> values) {
            addCriterion("realname not in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameBetween(String value1, String value2) {
            addCriterion("realname between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotBetween(String value1, String value2) {
            addCriterion("realname not between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andIdentityIsNull() {
            addCriterion("identity is null");
            return (Criteria) this;
        }

        public Criteria andIdentityIsNotNull() {
            addCriterion("identity is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityEqualTo(String value) {
            addCriterion("identity =", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotEqualTo(String value) {
            addCriterion("identity <>", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityGreaterThan(String value) {
            addCriterion("identity >", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityGreaterThanOrEqualTo(String value) {
            addCriterion("identity >=", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityLessThan(String value) {
            addCriterion("identity <", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityLessThanOrEqualTo(String value) {
            addCriterion("identity <=", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityLike(String value) {
            addCriterion("identity like", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotLike(String value) {
            addCriterion("identity not like", value, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityIn(List<String> values) {
            addCriterion("identity in", values, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotIn(List<String> values) {
            addCriterion("identity not in", values, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityBetween(String value1, String value2) {
            addCriterion("identity between", value1, value2, "identity");
            return (Criteria) this;
        }

        public Criteria andIdentityNotBetween(String value1, String value2) {
            addCriterion("identity not between", value1, value2, "identity");
            return (Criteria) this;
        }

        public Criteria andYellowvipIsNull() {
            addCriterion("yellowvip is null");
            return (Criteria) this;
        }

        public Criteria andYellowvipIsNotNull() {
            addCriterion("yellowvip is not null");
            return (Criteria) this;
        }

        public Criteria andYellowvipEqualTo(Byte value) {
            addCriterion("yellowvip =", value, "yellowvip");
            return (Criteria) this;
        }

        public Criteria andYellowvipNotEqualTo(Byte value) {
            addCriterion("yellowvip <>", value, "yellowvip");
            return (Criteria) this;
        }

        public Criteria andYellowvipGreaterThan(Byte value) {
            addCriterion("yellowvip >", value, "yellowvip");
            return (Criteria) this;
        }

        public Criteria andYellowvipGreaterThanOrEqualTo(Byte value) {
            addCriterion("yellowvip >=", value, "yellowvip");
            return (Criteria) this;
        }

        public Criteria andYellowvipLessThan(Byte value) {
            addCriterion("yellowvip <", value, "yellowvip");
            return (Criteria) this;
        }

        public Criteria andYellowvipLessThanOrEqualTo(Byte value) {
            addCriterion("yellowvip <=", value, "yellowvip");
            return (Criteria) this;
        }

        public Criteria andYellowvipIn(List<Byte> values) {
            addCriterion("yellowvip in", values, "yellowvip");
            return (Criteria) this;
        }

        public Criteria andYellowvipNotIn(List<Byte> values) {
            addCriterion("yellowvip not in", values, "yellowvip");
            return (Criteria) this;
        }

        public Criteria andYellowvipBetween(Byte value1, Byte value2) {
            addCriterion("yellowvip between", value1, value2, "yellowvip");
            return (Criteria) this;
        }

        public Criteria andYellowvipNotBetween(Byte value1, Byte value2) {
            addCriterion("yellowvip not between", value1, value2, "yellowvip");
            return (Criteria) this;
        }

        public Criteria andIsyearvipIsNull() {
            addCriterion("isyearvip is null");
            return (Criteria) this;
        }

        public Criteria andIsyearvipIsNotNull() {
            addCriterion("isyearvip is not null");
            return (Criteria) this;
        }

        public Criteria andIsyearvipEqualTo(Byte value) {
            addCriterion("isyearvip =", value, "isyearvip");
            return (Criteria) this;
        }

        public Criteria andIsyearvipNotEqualTo(Byte value) {
            addCriterion("isyearvip <>", value, "isyearvip");
            return (Criteria) this;
        }

        public Criteria andIsyearvipGreaterThan(Byte value) {
            addCriterion("isyearvip >", value, "isyearvip");
            return (Criteria) this;
        }

        public Criteria andIsyearvipGreaterThanOrEqualTo(Byte value) {
            addCriterion("isyearvip >=", value, "isyearvip");
            return (Criteria) this;
        }

        public Criteria andIsyearvipLessThan(Byte value) {
            addCriterion("isyearvip <", value, "isyearvip");
            return (Criteria) this;
        }

        public Criteria andIsyearvipLessThanOrEqualTo(Byte value) {
            addCriterion("isyearvip <=", value, "isyearvip");
            return (Criteria) this;
        }

        public Criteria andIsyearvipIn(List<Byte> values) {
            addCriterion("isyearvip in", values, "isyearvip");
            return (Criteria) this;
        }

        public Criteria andIsyearvipNotIn(List<Byte> values) {
            addCriterion("isyearvip not in", values, "isyearvip");
            return (Criteria) this;
        }

        public Criteria andIsyearvipBetween(Byte value1, Byte value2) {
            addCriterion("isyearvip between", value1, value2, "isyearvip");
            return (Criteria) this;
        }

        public Criteria andIsyearvipNotBetween(Byte value1, Byte value2) {
            addCriterion("isyearvip not between", value1, value2, "isyearvip");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNull() {
            addCriterion("passwd is null");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNotNull() {
            addCriterion("passwd is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdEqualTo(String value) {
            addCriterion("passwd =", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotEqualTo(String value) {
            addCriterion("passwd <>", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThan(String value) {
            addCriterion("passwd >", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("passwd >=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThan(String value) {
            addCriterion("passwd <", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThanOrEqualTo(String value) {
            addCriterion("passwd <=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLike(String value) {
            addCriterion("passwd like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotLike(String value) {
            addCriterion("passwd not like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdIn(List<String> values) {
            addCriterion("passwd in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotIn(List<String> values) {
            addCriterion("passwd not in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdBetween(String value1, String value2) {
            addCriterion("passwd between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotBetween(String value1, String value2) {
            addCriterion("passwd not between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("salt is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("salt is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("salt =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("salt <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("salt >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("salt >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("salt <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("salt <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("salt like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("salt not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("salt in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("salt not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("salt between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("salt not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andLgtmIsNull() {
            addCriterion("lgtm is null");
            return (Criteria) this;
        }

        public Criteria andLgtmIsNotNull() {
            addCriterion("lgtm is not null");
            return (Criteria) this;
        }

        public Criteria andLgtmEqualTo(Integer value) {
            addCriterion("lgtm =", value, "lgtm");
            return (Criteria) this;
        }

        public Criteria andLgtmNotEqualTo(Integer value) {
            addCriterion("lgtm <>", value, "lgtm");
            return (Criteria) this;
        }

        public Criteria andLgtmGreaterThan(Integer value) {
            addCriterion("lgtm >", value, "lgtm");
            return (Criteria) this;
        }

        public Criteria andLgtmGreaterThanOrEqualTo(Integer value) {
            addCriterion("lgtm >=", value, "lgtm");
            return (Criteria) this;
        }

        public Criteria andLgtmLessThan(Integer value) {
            addCriterion("lgtm <", value, "lgtm");
            return (Criteria) this;
        }

        public Criteria andLgtmLessThanOrEqualTo(Integer value) {
            addCriterion("lgtm <=", value, "lgtm");
            return (Criteria) this;
        }

        public Criteria andLgtmIn(List<Integer> values) {
            addCriterion("lgtm in", values, "lgtm");
            return (Criteria) this;
        }

        public Criteria andLgtmNotIn(List<Integer> values) {
            addCriterion("lgtm not in", values, "lgtm");
            return (Criteria) this;
        }

        public Criteria andLgtmBetween(Integer value1, Integer value2) {
            addCriterion("lgtm between", value1, value2, "lgtm");
            return (Criteria) this;
        }

        public Criteria andLgtmNotBetween(Integer value1, Integer value2) {
            addCriterion("lgtm not between", value1, value2, "lgtm");
            return (Criteria) this;
        }

        public Criteria andLxlgIsNull() {
            addCriterion("lxlg is null");
            return (Criteria) this;
        }

        public Criteria andLxlgIsNotNull() {
            addCriterion("lxlg is not null");
            return (Criteria) this;
        }

        public Criteria andLxlgEqualTo(Integer value) {
            addCriterion("lxlg =", value, "lxlg");
            return (Criteria) this;
        }

        public Criteria andLxlgNotEqualTo(Integer value) {
            addCriterion("lxlg <>", value, "lxlg");
            return (Criteria) this;
        }

        public Criteria andLxlgGreaterThan(Integer value) {
            addCriterion("lxlg >", value, "lxlg");
            return (Criteria) this;
        }

        public Criteria andLxlgGreaterThanOrEqualTo(Integer value) {
            addCriterion("lxlg >=", value, "lxlg");
            return (Criteria) this;
        }

        public Criteria andLxlgLessThan(Integer value) {
            addCriterion("lxlg <", value, "lxlg");
            return (Criteria) this;
        }

        public Criteria andLxlgLessThanOrEqualTo(Integer value) {
            addCriterion("lxlg <=", value, "lxlg");
            return (Criteria) this;
        }

        public Criteria andLxlgIn(List<Integer> values) {
            addCriterion("lxlg in", values, "lxlg");
            return (Criteria) this;
        }

        public Criteria andLxlgNotIn(List<Integer> values) {
            addCriterion("lxlg not in", values, "lxlg");
            return (Criteria) this;
        }

        public Criteria andLxlgBetween(Integer value1, Integer value2) {
            addCriterion("lxlg between", value1, value2, "lxlg");
            return (Criteria) this;
        }

        public Criteria andLxlgNotBetween(Integer value1, Integer value2) {
            addCriterion("lxlg not between", value1, value2, "lxlg");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("qq is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("qq is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("qq =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("qq <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("qq >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("qq >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("qq <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("qq <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("qq like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("qq not like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<String> values) {
            addCriterion("qq in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<String> values) {
            addCriterion("qq not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("qq between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("qq not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andRegipIsNull() {
            addCriterion("regip is null");
            return (Criteria) this;
        }

        public Criteria andRegipIsNotNull() {
            addCriterion("regip is not null");
            return (Criteria) this;
        }

        public Criteria andRegipEqualTo(Long value) {
            addCriterion("regip =", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipNotEqualTo(Long value) {
            addCriterion("regip <>", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipGreaterThan(Long value) {
            addCriterion("regip >", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipGreaterThanOrEqualTo(Long value) {
            addCriterion("regip >=", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipLessThan(Long value) {
            addCriterion("regip <", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipLessThanOrEqualTo(Long value) {
            addCriterion("regip <=", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipIn(List<Long> values) {
            addCriterion("regip in", values, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipNotIn(List<Long> values) {
            addCriterion("regip not in", values, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipBetween(Long value1, Long value2) {
            addCriterion("regip between", value1, value2, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipNotBetween(Long value1, Long value2) {
            addCriterion("regip not between", value1, value2, "regip");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsIsNull() {
            addCriterion("active_assets is null");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsIsNotNull() {
            addCriterion("active_assets is not null");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsEqualTo(Byte value) {
            addCriterion("active_assets =", value, "activeAssets");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsNotEqualTo(Byte value) {
            addCriterion("active_assets <>", value, "activeAssets");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsGreaterThan(Byte value) {
            addCriterion("active_assets >", value, "activeAssets");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsGreaterThanOrEqualTo(Byte value) {
            addCriterion("active_assets >=", value, "activeAssets");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsLessThan(Byte value) {
            addCriterion("active_assets <", value, "activeAssets");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsLessThanOrEqualTo(Byte value) {
            addCriterion("active_assets <=", value, "activeAssets");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsIn(List<Byte> values) {
            addCriterion("active_assets in", values, "activeAssets");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsNotIn(List<Byte> values) {
            addCriterion("active_assets not in", values, "activeAssets");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsBetween(Byte value1, Byte value2) {
            addCriterion("active_assets between", value1, value2, "activeAssets");
            return (Criteria) this;
        }

        public Criteria andActiveAssetsNotBetween(Byte value1, Byte value2) {
            addCriterion("active_assets not between", value1, value2, "activeAssets");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table memberfides0
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 21 17:38:55 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table memberfides0
     *
     * @mbg.generated Thu Dec 21 17:38:55 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}